import type { Metadata } from "next";
import "../globals.css";

import theme from "@/theme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Navbar from "@/components/Navbar";
import { Box } from "@mui/material";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider theme={theme}>
                    <Box
                        className="test"
                        maxWidth={1200}
                        height={"100vh"}
                        minHeight={"100vh"}
                        margin={"auto"}
                        pt={["56px", "64px"]}
                    >
                        <CssBaseline />
                        <Navbar />
                        <Box
                            component="main"
                            py={[2, 4]}
                            px={[1, 2]}
                            height={"100%"}
                        >
                            {children}
                        </Box>
                    </Box>
                </ThemeProvider>
            </body>
        </html>
    );
}
