import type { Metadata } from "next";
import "../globals.css";

import theme from "@/theme";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Navbar from "@/components/Navbar";
import { Box } from "@mui/material";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider theme={theme}>
                    <Box
                        maxWidth={1200}
                        display={"flex"}
                        flexDirection={"column"}
                        margin={"auto"}
                    >
                        <CssBaseline />
                        <Navbar />
                        {children}
                    </Box>
                </ThemeProvider>
            </body>
        </html>
    );
}
